-- MySQL Script generated by MySQL Workbench
-- Sat Feb 20 22:05:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema monikatsu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema monikatsu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `monikatsu` DEFAULT CHARACTER SET utf8 ;
USE `monikatsu` ;

-- -----------------------------------------------------
-- Table `monikatsu`.`line_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monikatsu`.`line_user` (
  `user_id` VARCHAR(45) NOT NULL,
  `line_user_token` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`, `line_user_token`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) ,
  UNIQUE INDEX `line_user_token_UNIQUE` (`line_user_token` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monikatsu`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monikatsu`.`user` (
  `id` VARCHAR(45) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `user_line_id` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `user_name`, `user_line_id`, `user_password`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `user_password_UNIQUE` (`user_password` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monikatsu`.`wakeup_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monikatsu`.`wakeup_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(45) NOT NULL,
  `wakeup_day` VARCHAR(45) NOT NULL,
  `wakeup_time` VARCHAR(45) NOT NULL,
  `created_at` VARCHAR(45) NOT NULL,
  `updated_at` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `monikatsu`.`wakeup_score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `monikatsu`.`wakeup_score` (
  `user_id` VARCHAR(45) NOT NULL,
  `score` VARCHAR(45) NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
