# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monikatsu-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monikatsu-server
  template:
    metadata:
      labels:
        app: monikatsu-server
    spec:
      containers:
        - name: monikatsu-server
          # Replace $GCLOUD_PROJECT with your project ID
          image: gcr.io/monikatsu-project/monikatsu-gke-test
          # This app listens on port 8080 for web traffic by default.
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "DkGFiwFGJzkjbjJ5"
            - name: DB_NAME
              value: "monikatsu_db"
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: "monikatsu_db"
            - name: DB_DRIVER
              value: "mysql"
