apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: monikatsu-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: monikatsu
spec:
  rules:
  - host: monikatsu.com
    http:
      paths:
      - path: /
        backend:
          serviceName: monikatsu-service
          servicePort: 80