service: session-manage

runtime: go113

main: ./server/

env_variables:
  ENV: "production"
  SERVER_PORT: ":9090"
  REDIS_HOST: "10.117.105.99"
  REDIS_PORT: "6379"

handlers:
  - url: /.*
    script: auto
vpc_access_connector:
  name: "projects/monikatsu-project/locations/asia-northeast1/connectors/monikatsu-vpc-connector"
# network:
#   name: default
