apiVersion: v1
kind: Service
metadata:
  name: manage-session
spec:
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app: manage-session
  type: LoadBalancer
