version: "3.7"
services:
  monikatsu-dev-session-server2:
    image: "motoyukikimura/session_grpc_server"
    container_name: monikatsu-dev-session-server2
    networks:
      - monikatsu-network
    ports:
      - ${GRPC_SERVER_PORT}:${GRPC_SERVER_PORT}
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - GRPC_SERVER_PORT=${GRPC_SERVER_PORT}
networks:
  monikatsu-network:
    driver: bridge
