version: "3.7"
services:
  monikatsu-dev-app-server3:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: monikatsu-dev-app-server3
    networks:
      - monikatsu-network
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_DRIVER=${DB_DRIVER}
      - GRPC_SERVER_PORT=${GRPC_SERVER_PORT}
      - GRPC_SERVER_HOST_CONTAINER=${GRPC_SERVER_HOST_CONTAINER}
    links:
      - monikatsu-dev-session-server2

  monikatsu-dev-session-server2:
    image: "motoyukikimura/session_grpc_server"
    container_name: monikatsu-dev-session-server2
    networks:
      - monikatsu-network
    ports:
      - ${GRPC_SERVER_PORT}:${GRPC_SERVER_PORT}
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - GRPC_SERVER_PORT=${GRPC_SERVER_PORT}

networks:
  monikatsu-network:
    driver: bridge
