version: "3.7"
services:
  monikatsu-dev-app-server:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: monikatsu-dev-app-server
    networks:
      - monikatsu-network
    ports:
      - 127.0.0.1:8080:${APP_SERVER_PORT}
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_DRIVER=${DB_DRIVER}
networks:
  monikatsu-network:
    driver: bridge
