name: Go
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - 1.15
    name: Go test
    steps:
      - uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          version: ${{ matrix.go }}
      - name: Run go mod download
        run: go mod download
      - name: Run tests
        run: go test -race -v ./...
